### ISSUE TITLE
Some small bugs I encountered during bug testing

### ISSUE THREAD

**Issue by thelegendaryjohn** [Cubed-Development/Modern-Warfare-Cubed#209]
## Describe the bugs

- ~~Minecraft crashes when attempting to use _MWC Tablet_~~ **(Planned to be fixed on 0.1)**
- ~~_GPNVG-18 Nightvision Helmet_ does not move with the head~~ **(Planned to be fixed on 0.1)**
- _Flash Grenade_ only works when standing directly above it
- _KS-23_ only loads 3 shells when empty (still can continue to load it fully)
- When reloading a gun while aiming, it won’t un-aim upon releasing RMB afterward, only after clicking RMB again will it un-aim

## Crash report for MWC Tablet bug
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  weaponlib (Modern-Warfare-Cubed-0.1-Dev-14.jar)
  SecurityCraftLoadingPlugin ([1.12.2]+SecurityCraft+v1.9.7.jar)
  ShutdownPatcher (mcef-1.12.2-1.11b-coremod.jar)
  TLSkinCapeHookLoader (tlskincape_1.12.2-1.4.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 7/17/23 12:16 PM
Description: Unexpected error

java.lang.ClassCastException: net.minecraft.entity.passive.EntityVillager cannot be cast to net.minecraft.client.entity.EntityPlayerSP
	at com.paneedah.weaponlib.perspective.WirelessCameraPerspective.updateWatchablePlayer(WirelessCameraPerspective.java:109)
	at com.paneedah.weaponlib.perspective.RemoteFirstPersonPerspective.update(RemoteFirstPersonPerspective.java:43)
	at com.paneedah.weaponlib.ClientEventHandler.onRenderTickEvent(ClientEventHandler.java:364)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_86_ClientEventHandler_onRenderTickEvent_RenderTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onRenderTickStart(FMLCommonHandler.java:355)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.paneedah.weaponlib.perspective.WirelessCameraPerspective.updateWatchablePlayer(WirelessCameraPerspective.java:109)
	at com.paneedah.weaponlib.perspective.RemoteFirstPersonPerspective.update(RemoteFirstPersonPerspective.java:43)
	at com.paneedah.weaponlib.ClientEventHandler.onRenderTickEvent(ClientEventHandler.java:364)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_86_ClientEventHandler_onRenderTickEvent_RenderTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Johnny'/1643, l='MpServer', x=302.50, y=74.00, z=304.82]]
	Chunk stats: MultiplayerChunkCache: 272, 272
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (256,64,244), Chunk: (at 0,4,4 in 16,15; contains blocks 256,0,240 to 271,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 3965 game time, 3965 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 91 total; [EntityBat['Bat'/2311, l='MpServer', x=352.75, y=42.10, z=269.25], EntityBat['Bat'/2313, l='MpServer', x=351.34, y=48.10, z=268.57], EntitySheep['Sheep'/18, l='MpServer', x=222.50, y=66.00, z=287.50], EntitySheep['Sheep'/20, l='MpServer', x=227.19, y=66.00, z=289.50], EntitySheep['Sheep'/21, l='MpServer', x=225.50, y=66.00, z=290.50], EntitySheep['Sheep'/22, l='MpServer', x=236.45, y=63.00, z=238.55], EntitySheep['Sheep'/23, l='MpServer', x=241.64, y=64.00, z=236.01], EntitySheep['Sheep'/24, l='MpServer', x=245.48, y=63.00, z=242.24], EntitySheep['Sheep'/25, l='MpServer', x=239.50, y=63.00, z=238.50], EntitySheep['Sheep'/26, l='MpServer', x=242.50, y=63.00, z=252.50], EntitySheep['Sheep'/27, l='MpServer', x=245.55, y=63.00, z=252.22], EntitySheep['Sheep'/28, l='MpServer', x=241.50, y=63.00, z=248.50], EntitySheep['Sheep'/29, l='MpServer', x=242.50, y=63.00, z=259.50], EntityChicken['Chicken'/36, l='MpServer', x=267.37, y=64.00, z=285.86], EntityChicken['Chicken'/37, l='MpServer', x=259.85, y=64.00, z=285.62], EntityChicken['Chicken'/38, l='MpServer', x=255.89, y=65.00, z=292.26], EntityChicken['Chicken'/39, l='MpServer', x=267.10, y=64.00, z=290.33], EntityVillager['Villager'/40, l='MpServer', x=264.50, y=64.00, z=298.61], EntityVillager['Villager'/41, l='MpServer', x=260.50, y=66.00, z=304.50], EntityVillager['Villager'/42, l='MpServer', x=264.52, y=64.00, z=305.59], EntityChicken['Chicken'/43, l='MpServer', x=270.50, y=64.00, z=226.50], EntitySkeleton['Skeleton'/2347, l='MpServer', x=229.29, y=36.00, z=260.51], EntityChicken['Chicken'/46, l='MpServer', x=273.49, y=65.00, z=232.19], EntitySkeleton['Skeleton'/2350, l='MpServer', x=241.21, y=29.00, z=242.80], EntityChicken['Chicken'/47, l='MpServer', x=278.79, y=69.00, z=253.54], EntityChicken['Chicken'/48, l='MpServer', x=272.53, y=69.00, z=253.66], EntityChicken['Chicken'/49, l='MpServer', x=266.15, y=67.00, z=249.53], EntityChicken['Chicken'/50, l='MpServer', x=267.28, y=67.00, z=254.88], EntityVillager['Villager'/51, l='MpServer', x=269.80, y=63.94, z=307.46], EntityVillager['Villager'/52, l='MpServer', x=270.67, y=63.94, z=308.61], EntityVillager['Villager'/53, l='MpServer', x=276.51, y=65.00, z=297.57], EntityVillager['Villager'/54, l='MpServer', x=269.51, y=65.00, z=318.46], EntityChicken['Chicken'/60, l='MpServer', x=285.77, y=64.00, z=228.86], EntityChicken['Chicken'/61, l='MpServer', x=297.49, y=64.01, z=245.07], EntityZombie['Zombie'/2365, l='MpServer', x=274.29, y=46.00, z=292.51], EntityChicken['Chicken'/62, l='MpServer', x=292.50, y=64.00, z=244.16], EntityChicken['Chicken'/63, l='MpServer', x=299.50, y=64.00, z=227.95], EntityChicken['Chicken'/64, l='MpServer', x=281.50, y=64.00, z=275.50], EntityChicken['Chicken'/65, l='MpServer', x=282.50, y=64.00, z=273.50], EntityChicken['Chicken'/66, l='MpServer', x=278.59, y=64.00, z=270.83], EntityChicken['Chicken'/67, l='MpServer', x=279.63, y=64.00, z=284.89], EntityVillager['Villager'/68, l='MpServer', x=313.46, y=62.94, z=308.75], EntityZombie['Zombie'/2372, l='MpServer', x=275.26, y=46.00, z=290.53], EntityChicken['Chicken'/69, l='MpServer', x=303.50, y=65.00, z=251.50], EntityChicken['Chicken'/70, l='MpServer', x=304.50, y=65.00, z=252.50], EntityChicken['Chicken'/71, l='MpServer', x=304.50, y=65.00, z=253.50], EntityChicken['Chicken'/72, l='MpServer', x=297.51, y=65.00, z=255.17], EntityVillager['Villager'/73, l='MpServer', x=302.54, y=63.94, z=280.80], EntityChicken['Chicken'/74, l='MpServer', x=325.22, y=64.00, z=279.41], EntityBat['Bat'/2378, l='MpServer', x=230.51, y=25.18, z=275.50], EntityChicken['Chicken'/75, l='MpServer', x=306.29, y=64.00, z=297.83], EntityChicken['Chicken'/76, l='MpServer', x=308.46, y=64.00, z=268.80], EntityChicken['Chicken'/77, l='MpServer', x=295.39, y=64.00, z=268.89], EntityVillager['Villager'/78, l='MpServer', x=295.54, y=65.00, z=310.56], EntityVillager['Villager'/79, l='MpServer', x=283.14, y=65.00, z=314.25], EntityHorse['Horse'/80, l='MpServer', x=311.86, y=63.00, z=320.50], EntityHorse['Horse'/81, l='MpServer', x=295.15, y=64.00, z=339.92], EntityBat['Bat'/2385, l='MpServer', x=317.67, y=45.04, z=257.21], EntityHorse['Horse'/82, l='MpServer', x=310.78, y=63.00, z=320.48], EntityHorse['Horse'/83, l='MpServer', x=304.13, y=64.00, z=333.05], EntityVillager['Villager'/84, l='MpServer', x=293.48, y=63.94, z=335.98], EntityItem['item.item.mwc_wcam'/2390, l='MpServer', x=308.46, y=63.00, z=318.76], EntityVillager['Villager'/92, l='MpServer', x=310.52, y=65.00, z=314.57], EntityVillager['Villager'/93, l='MpServer', x=325.31, y=65.00, z=316.42], EntityVillager['Villager'/94, l='MpServer', x=303.70, y=65.00, z=305.70], EntityVillager['Villager'/95, l='MpServer', x=307.47, y=64.00, z=318.12], EntityChicken['Chicken'/96, l='MpServer', x=323.80, y=64.00, z=316.89], EntityChicken['Chicken'/97, l='MpServer', x=330.75, y=64.00, z=332.17], EntityChicken['Chicken'/98, l='MpServer', x=338.19, y=65.00, z=326.51], EntityChicken['Chicken'/99, l='MpServer', x=341.19, y=64.00, z=329.51], EntityHorse['Horse'/101, l='MpServer', x=306.11, y=64.00, z=331.56], EntityChicken['Chicken'/107, l='MpServer', x=337.14, y=63.00, z=318.18], EntityChicken['Chicken'/108, l='MpServer', x=343.50, y=63.00, z=311.50], EntityChicken['Chicken'/109, l='MpServer', x=346.50, y=63.00, z=322.19], EntityChicken['Chicken'/110, l='MpServer', x=339.65, y=63.00, z=309.48], EntityHorse['Horse'/111, l='MpServer', x=334.95, y=64.00, z=302.56], EntityHorse['Horse'/112, l='MpServer', x=312.13, y=64.00, z=288.06], EntityHorse['Horse'/113, l='MpServer', x=335.80, y=64.00, z=291.16], EntityHorse['Horse'/114, l='MpServer', x=339.87, y=64.00, z=288.13], EntityPlayerSP['Johnny'/1643, l='MpServer', x=302.50, y=74.00, z=304.82], EntityChicken['Chicken'/134, l='MpServer', x=377.50, y=64.00, z=237.50], EntityChicken['Chicken'/135, l='MpServer', x=381.50, y=64.00, z=237.50], EntityChicken['Chicken'/136, l='MpServer', x=381.94, y=64.00, z=237.58], EntityChicken['Chicken'/137, l='MpServer', x=381.50, y=64.00, z=238.50], EntitySkeleton['Skeleton'/2195, l='MpServer', x=352.45, y=44.00, z=275.01], EntitySpider['Spider'/2223, l='MpServer', x=351.50, y=44.00, z=279.50], EntityCreeper['Creeper'/1977, l='MpServer', x=329.50, y=43.00, z=251.50], EntityZombie['Zombie'/2241, l='MpServer', x=294.50, y=55.00, z=382.50], EntitySpider['Spider'/2255, l='MpServer', x=317.50, y=43.00, z=260.50], EntitySkeleton['Skeleton'/2018, l='MpServer', x=363.50, y=47.00, z=300.50], EntityCreeper['Creeper'/2297, l='MpServer', x=359.50, y=47.00, z=266.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1927748032 bytes (1838 MB) / 3422552064 bytes (3264 MB) up to 5435817984 bytes (5184 MB)
	JVM Flags: 7 total; -Xmx5172M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 3, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G5 10 mods loaded, 10 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                         | Version      | Source                              | Signature                                |
	|:------ |:-------------------------- |:------------ |:----------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                  | 1.12.2       | minecraft.jar                       | None                                     |
	| LCHIJA | mcp                        | 9.42         | minecraft.jar                       | None                                     |
	| LCHIJA | FML                        | 8.0.99.99    | forge-1.12.2-14.23.5.2860.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                      | 14.23.5.2860 | forge-1.12.2-14.23.5.2860.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | securitycraft              | v1.9.7       | [1.12.2]+SecurityCraft+v1.9.7.jar   | None                                     |
	| LCHIJA | mcef                       | 1.11         | mcef-1.12.2-1.11b.jar               | None                                     |
	| LCHIJA | redcore                    | 0.2          | Red-Core-0.2.jar                    | None                                     |
	| LCHIJA | mwc                        | 0.1-Dev-14   | Modern-Warfare-Cubed-0.1-Dev-14.jar | None                                     |
	| LCHIJA | tlauncher_custom_cape_skin | 1.4          | tlskincape_1.12.2-1.4.jar           | None                                     |
	| LCHIJA | webdisplays                | 1.1          | webdisplays-1.12.2-1.1.jar          | None                                     |

	Loaded coremods (and transformers): 
weaponlib (Modern-Warfare-Cubed-0.1-Dev-14.jar)
  com.paneedah.weaponlib.core.WeaponlibClassTransformer
SecurityCraftLoadingPlugin ([1.12.2]+SecurityCraft+v1.9.7.jar)
  
ShutdownPatcher (mcef-1.12.2-1.11b-coremod.jar)
  net.montoyo.mcef.coremod.ShutdownPatcher
TLSkinCapeHookLoader (tlskincape_1.12.2-1.4.jar)
  gloomyfolken.hooklib.minecraft.PrimaryClassTransformer
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 31.0.101.2111' Renderer: 'Intel(R) HD Graphics 520'
	Launched Version: ForgeOptiFine 1.12.2
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 520 GL version 4.6.0 - Build 31.0.101.2111, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 - Build 31.0.101.2111
	OpenGlRenderer: Intel(R) HD Graphics 520
	OpenGlVendor: Intel
	CpuCount: 4
```

## Reproducibility
Consistent, it happens every time I try to use the MWC Tablet after attaching a camera to an entity

## Steps to reproduce
- Step 1: Attach a camera to an entity
- Step 2: Switch to the tablet in your hotbar

#
**Versions:**
- Modern Warfare Cubed: MWC 0.1-Dev-14
- Forge: 1.12.2-14.23.5.2860
- Java: JDK 1.8.0_351-b10
- Java JVM: 25.351-b10 (64-bit)

**Specification:**
- OS: Windows 10 Pro
- CPU: Intel Core i5-6300U 2.40GHz
- GPU: Intel HD Graphic 520
- RAM Allocated: approx. 5GB

**Comment by Desoroxxx** [comment]
Please send crash report, we can't do anything without one

**Comment by thelegendaryjohn** [comment]
Ah yes sry, forgot the crash report

**Comment by thelegendaryjohn** [comment]
@Desoroxxx
**UPDATE:** Added the crash report, reproducibility and steps to reproduce

**Comment by thelegendaryjohn** [comment]
@Paneedah Got it!
How about the other 3 bugs tho, will they be fixed as well?

**Comment by Desoroxxx** [comment]
Yes some of them where already planned to be fixed

**Comment by strubium** [comment]
.withName("ks23")
//      .withCapacity(CommonProxy.Remington870Mag)
        .withAmmoCapacity(4)
        .withMaxBulletsPerReload(3)

**Comment by Desoroxxx** [comment]
All of this is either already fixed, not an issue, or a duplicate, closing this

**Comment by notdeadpool456** [comment]
> ` .withName("ks23") // .withCapacity(CommonProxy.Remington870Mag) .withAmmoCapacity(4) .withMaxBulletsPerReload(3) `

Ye the gun literally has a 3 round magazine IRL and the 4th is a breach load.

**Comment by thelegendaryjohn** [comment]
@notdeadpool456 Got it, thnx!
