### ISSUE TITLE
Crash on Gun Firing

### ISSUE THREAD

**Issue by MetaF0rce** [Cubed-Development/Modern-Warfare-Cubed#262]
Use only this mod in 1.12.2 and create new world and shoot a gun. Use modrinth and redcore

## Expected behavior

Crashes with "shutting down internal servers" when I fire a gun

## Logs or/and crash reports

WARNING: coremods are present:
  weaponlib (Modern-Warfare-Cubed-0.1-Dev-14.jar)
Contact their authors BEFORE contacting forge

Time: 8/24/23 2:51 PM
Description: Unexpected error

org.lwjgl.opengl.OpenGLException: Invalid enum (1280)
	at org.lwjgl.opengl.Util.checkGLError(Util.java:59)
	at org.lwjgl.opengl.DrawableGL.checkGLError(DrawableGL.java:82)
	at org.lwjgl.opengl.Display.swapBuffers(Display.java:617)
	at org.lwjgl.opengl.Display.update(Display.java:646)
	at org.lwjgl.opengl.Display.update(Display.java:628)
	at net.minecraft.client.Minecraft.func_175601_h(Minecraft.java:1205)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1153)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

## Versions

- Modern Warfare Cubed: [e.g. MWC-0.1-Dev-1] 
- Forge: 1.12.2 through modrinth
- Java: [e.g. JDK 8 - 352-b08]
- Java JVM: [e.g. Hotspot]

## Specification:

- OS: Windows 11
- CPU: Ryzen 7 5800X
- GPU: 3050ti
- RAM Allocated: 32gb pc total

***All of these info below are not necessary but may become necessary depending on the issue***

- CPU Speed: [e.g. 3.80GHz Boost around 4.25Ghz]
- CPU Core: [e.g. 8 (Attention Core not logical core)]
- CPU Threads: [e.g. 16 (Named Logical processors in task manager)]
- RAM Size: [e.g. 32GB]
- RAM Speed: [e.g. 2666MHz]
- Storage Type: [HDD or SSD]
- GPU VRAM: [e.g. 2GB]

> Most of these information can be found in the task manager

## Additional context

***Add any other context about the problem here.***

**Comment by Desoroxxx** [comment]
Please fill the template correctly
