### ISSUE TITLE
Crash caused by Duplicate stat id compatibility issue [SOLVED]

### ISSUE THREAD

**Issue by saltygammer31230** [Cubed-Development/Modern-Warfare-Cubed#283]
## This has Been solved

> if you have the same problem go down to comments there's a link to the fix

## Describe the bug

***A clear and concise description of what the bug is.***

> The crash is caused by sevendaystomine being with MWC and it displays Duplicate stat id 
## Reproducibility
>NOTE: this was on a forge server ver 14.23.5.2860 and Optifine didn't change anything.

- [x] I reproduced this issue with only the mods in question >7DTM with MWC.
- [ ] I am unable to reproduce this issue consistently.

## To Reproduce

***Steps to reproduce the behavior:***

1.  Put sevendaystomine and MWC in together. NOTE: this was on a forge server ver 14.23.5.2860

## Logs or/and crash reports

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Red Core (!Red-Core-0.4.jar)
  weaponlib (Modern-Warfare-Cubed-0.1-Dev-14.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 9/24/23 6:43 PM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from 7 Days to Mine (sevendaystomine)
Caused by: java.lang.RuntimeException: Duplicate stat id: "TranslatableComponent{key='stat.entityKill', args=[TranslatableComponent{key='entity.soldier.name', args=[], siblings=[], style=Style{hasParent=true, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}" and "TranslatableComponent{key='stat.entityKill', args=[TranslatableComponent{key='entity.soldier.name', args=[], siblings=[], style=Style{hasParent=true, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}" at id stat.killEntity.soldier
	at net.minecraft.stats.StatBase.func_75971_g(SourceFile:41)
	at net.minecraft.stats.StatList.func_151182_a(StatList.java:305)
	at net.minecraft.entity.EntityList$EntityEggInfo.<init>(EntityList.java:450)
	at net.minecraftforge.fml.common.registry.EntityRegistry.registerEgg(EntityRegistry.java:242)
	at net.minecraftforge.fml.common.registry.EntityRegistry.registerModEntity(EntityRegistry.java:193)
	at nuparu.sevendaystomine.proxy.CommonProxy.registerEntity(CommonProxy.java:486)
	at nuparu.sevendaystomine.proxy.CommonProxy.registerEntity(CommonProxy.java:507)
	at nuparu.sevendaystomine.proxy.CommonProxy.registerEntities(CommonProxy.java:415)
	at nuparu.sevendaystomine.proxy.CommonProxy.init(CommonProxy.java:222)
	at nuparu.sevendaystomine.SevenDaysToMine.init(SevenDaysToMine.java:409)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_381, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4119788336 bytes (3928 MB) / 5231869952 bytes (4989 MB) up to 5231869952 bytes (4989 MB)
	JVM Flags: 2 total; -Xmx5190M -Xms5190M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID              | Version         | Source                              | Signature                                |
	|:----- |:--------------- |:--------------- |:----------------------------------- |:---------------------------------------- |
	| LCHI  | minecraft       | 1.12.2          | minecraft.jar                       | None                                     |
	| LCHI  | mcp             | 9.42            | minecraft.jar                       | None                                     |
	| LCHI  | FML             | 8.0.99.99       | server.jar                          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | forge           | 14.23.5.2860    | server.jar                          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | redcore         | 0.4             | !Red-Core-0.4.jar                   | None                                     |
	| LCHI  | mwc             | 0.1-Dev-14      | Modern-Warfare-Cubed-0.1-Dev-14.jar | None                                     |
	| LCHE  | sevendaystomine | 1.12.2-1.0.2.10 | sevendaystomine-1.12.2-1.0.2.10.jar | None                                     |

	Loaded coremods (and transformers): 
Red Core (!Red-Core-0.4.jar)
  
weaponlib (Modern-Warfare-Cubed-0.1-Dev-14.jar)
  com.paneedah.weaponlib.core.WeaponlibClassTransformer
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

## Versions

- Modern Warfare Cubed: [MWC-0.1-Dev-1] 
- Forge: [server 1.12.2 - 14.23.5.2860]
- Java: [JDK 8-381 64bit]
- Java JVM: [N/A]

## Specification:

- OS: [Windows 10]
- CPU: [Ryzen 9 5950X]
- GPU: [Radeon RX 6700 XT]
- RAM Allocated: [14GB]

***All of these info below are not necessary but may become necessary depending on the issue***

- CPU Speed: [3.80GHz OC - Single core Boost 5.15GHz - OC Multicore Boost 4.80GHz]
- CPU Core: [16]
- CPU Threads: [32]
- RAM Size: [32GB]
- RAM Speed: [3000MHz]
- Storage Type: [SSD M.2]
- GPU VRAM: [12GB]

> Most of these information can be found in the task manager

## Additional context

The 7DTM dev has stopped working on 1.12.2 so on his end there wont be help.
Please don't waste your time with this if you have more pressing matters as this seems to be a case of a compatibility issue.

**Comment by KorewaLidesu** [comment]
Have you consider try [DTM Integrations](https://www.curseforge.com/minecraft/mc-mods/dtm-integrations)?
